#
# validate yml:
# circleci config validate
#

version: 2.1

orbs:
  # tools: naturalcycles/tools@volatile
  tools: naturalcycles/tools@dev:1

#
# Defaults
#
defaults: &defaults
  resource_class: xlarge
  docker:
    - image: naturalcycles/ci-node:latest
  working_directory: ~/repo

restore_cache: &restore_cache
  key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "package.json" }}

save_cache: &save_cache
  paths:
    - node_modules
  key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "package.json" }}

test: &test
  name: Test
  command: |
    cc-test-reporter before-build
    yarn test-ci
    cc-test-reporter after-build -t lcov ./coverage/lcov.info

release: &release
  name: Release (if needed)
  command: yarn release

#
# Jobs
#
jobs:
  build-job:
    <<: *defaults
    environment:
      CC_TEST_REPORTER_ID: 791311fd4ab23bf9d0246fe1d1b4b589656a0de6d8a9a1a6d91a098b8816ea85
    steps:
      - checkout

      # yarn
      - restore_cache: *restore_cache
      - run: yarn --pure-lockfile
      - save_cache: *save_cache

      # build
      - run: yarn build-prod

      # test
      - run: *test

      # release
      - run: *release

      - store_test_results:
          path: report
      - store_artifacts:
          path: report
          destination: report
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

  nightly-job:
    <<: *defaults
    steps:
      - checkout

      # yarn (no cache)
      - run: yarn --pure-lockfile

      - run: yarn build
      - run: yarn test-ci

      - run:
          name: Report failure
          when: on_fail
          command: |
            echo todo

      - store_test_results:
          path: report
      - store_artifacts:
          path: report
          destination: report

  hello-job:
    executor: tools/node
    steps:
      - checkout
      - tools/yarn_deps_lib

#
# Workflows
#
workflows:
  version: 2
  default-workflow:
    jobs:
      - build-job:
          filters:
            branches:
              only: master
      - hello-job

  nightly-workflow:
    triggers:
      - schedule:
          cron: '0 4 * * *' # 04:00 every day
          filters:
            branches:
              only: master
    jobs:
      - nightly-job
