#
# validate yml:
# circleci config validate -c .circleci/config.yml
#

version: 2

#
# Defaults
#
defaults: &defaults
  resource_class: xlarge
  docker:
    - image: naturalcycles/ci-node:latest
  working_directory: ~/repo

restore_cache: &restore_cache
  key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}

save_cache: &save_cache
  paths:
    - node_modules
  key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}

npm_token: &npm_token echo -e "always-auth=true\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

git_msg: &git_msg echo 'export GIT_MSG=`git log -1 --pretty=%B`' >> $BASH_ENV

npm_publish: &npm_publish
  name: npm publish
  command: |
    NPM_TAG=latest
    NPM_VER_NEXT=1.0.$CIRCLE_BUILD_NUM
    npm version $NPM_VER_NEXT
    npm publish --access public --tag $NPM_TAG

test: &test
  name: Test
  command: |
    yarn build
    cc-test-reporter before-build
    yarn test-ci
    cc-test-reporter after-build -t lcov ./coverage/lcov.info

#
# Jobs
#
jobs:
  build-job:
    <<: *defaults
    environment:
      CC_TEST_REPORTER_ID: 791311fd4ab23bf9d0246fe1d1b4b589656a0de6d8a9a1a6d91a098b8816ea85
    steps:
      - checkout

      # env variables
      - run: *git_msg

      # yarn
      - restore_cache: *restore_cache
      - run: *npm_token
      - run: yarn --pure-lockfile
      - save_cache: *save_cache

      # build
      - run: yarn build-prod

      # npm publish
      - run: *npm_publish

      # test
      - run: *test

      - store_test_results:
          path: report
      - store_artifacts:
          path: report
          destination: report
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

#
# Workflows
#
workflows:
  version: 2
  default-workflow:
    jobs:
      - build-job:
          filters:
            branches:
              only: master
