
version: 2
jobs:
  publish-job:
    docker:
      - image: naturalcycles/ci-node:latest
    working_directory: ~/repo
    steps:
      - checkout

      # env
      - run: echo 'export GIT_MSG=`git log -1 --pretty=%B`' >> $BASH_ENV

      # npm publish
      - run:
          name: npm publish
          command: |
            NPM_TAG=latest
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            NPM_VER_NEXT=1.0.$CIRCLE_BUILD_NUM
            npm version $NPM_VER_NEXT -m "version: %s [ci skip]: $GIT_MSG"
            npm publish --access public --tag $NPM_TAG

workflows:
  version: 2
  publish-workflow:
    jobs:
      - publish-job:
          filters:
            branches:
              only: master
