#
# validate yml:
# circleci config validate
#

version: 2.1

orbs:
  # tools: naturalcycles/tools@volatile
  tools: naturalcycles/tools@dev:1

#
# Jobs
#
jobs:
  build-job:
    executor: tools/node
    steps:
      - checkout

      # yarn
      - tools/install_yarn_deps_lib

      # build
      - run: yarn build-prod

      # release
      # - run: *release

  test-job:
    executor: tools/node
    environment:
      CC_TEST_REPORTER_ID: 791311fd4ab23bf9d0246fe1d1b4b589656a0de6d8a9a1a6d91a098b8816ea85
    steps:
      - checkout

      # yarn
      - tools/install_yarn_deps_lib

      # build
      - run: yarn build

      # test
      - tools/test_ci

      - tools/store_test_artifacts

  nightly-job:
    executor: tools/node
    steps:
      - checkout

      # yarn (no cache)
      - run: yarn --pure-lockfile

      - run: yarn build
      - run: yarn test-ci

      - run:
          name: Report failure
          when: on_fail
          command: |
            echo todo

      - tools/store_test_artifacts

#
# Workflows
#
workflows:
  version: 2
  default-workflow:
    jobs:
      - build-job:
          filters:
            branches:
              only:
                - master
                - orbs

  nightly-workflow:
    triggers:
      - schedule:
          cron: '0 4 * * *' # 04:00 every day
          filters:
            branches:
              only: master
    jobs:
      - nightly-job
