name: Actions

on: [push]

jobs:
  test-job:
    name: test-job
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=3200'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ github.repository }}-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-deps-v1

      - name: deps
        run: |
          # echo -e "always-auth=true\n//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn --frozen-lockfile

      - name: build
        run: |
          yarn build

      - name: test
        run: |
          echo $NODE_OPTIONS
          yarn test-ci

      - uses: actions/upload-artifact@v1
        with:
          name: unit.xml
          path: tmp/jest/unit.xml
      - uses: actions/upload-artifact@v1
        with:
          name: coverage-unit
          path: coverage/lcov-report
